### ISSUE TITLE
Issue Đầu Tiên.

### ISSUE THREAD

**Issue by baronha** [anhquan291/react-native-animated-otp-input#1]
Hi bạn,
Cảm ơn bạn đã chia sẻ thư viện xịn xò này nhá.

Mình chẳng bị bug gì cả. Giờ mình close issue đây. Mình đến đây để trả thù hồi xưa bạn tại issue tiếng Việt bên repo của mình.
https://github.com/baronha/react-native-multiple-image-picker/issues/3

Cám ơn bạn nhiều ạ.

**Comment by anhquan291** [comment]
🤪🤪🤪🤪
